### ISSUE TITLE
There is a potential runtime exception

### ISSUE THREAD

**Issue by Liloveyang** [attenton/APIComments#1]
Hello,

First of all i want to thank you for sharing your code.
But when I was operating some of my files, there was a runtime exception.

I found that it was thrown by the main method in src/utils/parseComment.java,
when  parse some files that are not syntax complete, exception
of type com.github.javaparser.ParseProblemException may occur due to the failure of the parse,.

However, I didn't know that this exception would happen before, resulting in a sudden interruption of my operation,

so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop.
Thank you!

such as a not syntax complete java file content: 

```
public class Test {

private  BigDecimal d;

public Test(BigDecimal val) {
    d =  val;
}
public static void main(String[] args) throws FileNotFoundException {
    FileInputStream fileInputStream = new FileInputStream(new File(""));
    getCompilationUnit(fileInputStream);
```

**Comment by attenton** [comment]
Ok, I will fix it. Thanks
